fix: le sélecteur d'utilisateurs affiche par défaut l'email quand le nom n'existe pas encore
mano-sesan/mano pull request #280
Opened 2024-06-04 16:25 UTC by arnaudambro

2024-06-06 13:04 UTC, rap2hpoutre requested changes
VOir le commentaire

2024-06-06 13:04 UTC, rap2hpoutre commented on api/src/controllers/user.js
> +          email: user.email,
Hum du coup je ne sais pas si c'est un bon move. En effet, ça veut dire qu'on donne les emails de toute l'orga à n'importe qui.
Peut-être qu'on devrait limiter l'email uniquement pour les admins, et pour les utilisateurs qui n'ont pas accès à utilisateur, on mettrait juste "Nom d'utilisateur non renseigné" ou "???".
Ou au pire du pire un email partiellement masqué, mais je pense que c'est se faire chier pour rien.

2024-06-06 14:27 UTC, arnaudambro commented on api/src/controllers/user.js
> +          email: user.email,
on peut demander aux autres ?

2024-06-06 14:35 UTC, rap2hpoutre commented on api/src/controllers/user.js
> +          email: user.email,
Je pense qu'on peut décider tout seuls : 

- Les infos des utilisateurs est souvent cité comme faille. 
   - Si on a les emails, on a la moitié du login
   - Les utilisateurs n'ont pas à connaitre les emails
   - Si on l'a désactivé à une époque c'est surement par protection
- c'est moi qui ai remonté ça donc dans le fond ça n'a pas l'air d'être un problème, on corrige un truc ici "pour se faire plaisir"

En fait selon moi, c'est une décision liée à la sécurité et aux bonnes pratiques. Dans les applications en général, on ne retourne pas la liste des emails, j'en suis sûr on ne le fait pas au SNU ou d'ailleurs nulle part. On les retourne juste pour les gens qui peuvent gérer les utilisateurs

Je suis quand même ouvert à la discussion, mais ce sera ma réponse si on demande aux autres !

2024-06-11 08:10 UTC, rap2hpoutre commented
Vu à l'oral on ne les affiche pas

2024-06-11 08:37 UTC, merged