feat(app): nouvelle librairie de chiffrement pour aller peut-être plus vite
mano-sesan/mano pull request #714
Opened 2024-11-11 18:48 UTC by arnaudambro

2024-11-11 19:28 UTC, arnaudambro commented on app/src/components/Search.js
désolé ça n'a aucun rapport mais y'avait un warning de react sur `Search.defaultProps deprecated` qui m'a bien pollué
j'essaye de mettre ça dans une autre PR

2024-11-12 10:39 UTC, rap2hpoutre requested changes
J'ai une erreur en modifiant une personne : 

> Error: Value is undefined, expected an Object
    at jsi_crypto_secretbox_easy (native)
    at crypto_secretbox_easy (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.sesan.mano&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:194721:46)
    at ?anon_0_ (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.sesan.mano&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:194285:97)
    at next (native)
    at asyncGeneratorStep (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.sesan.mano&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:24442:19)
    at _next (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.sesan.mano&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:24456:29)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)] {
  "extra": {
    "path": "/person/042f0cef-9c95-4b17-aa38-53a1c48eb712",
    "query": {},
    "method": "PUT",
    "body": {
      "_id": "042f0cef-9c95-4b17-aa38-53a1c48eb712",
      "createdAt": "2024-10-10T15:41:05.894Z",
      "decrypted": {
        "name": "01z37savua",
        "gender": "Femme",
        "assignedTeams": [
          "0cb45198-f9de-406a-88de-b418e8f899de"
        ],
        "followedSince": "2023-11-17T20:19:39.030Z",
        "history": [
          {
            "date": "2024-11-12T10:38:30.939Z",
            "user": "0d8460f3-f6a4-40b5-b49e-4a1f37b57bdf",
            "data": {
              "gender": {
                "newValue": "Femme"
              }
            }
          }
        ]
      },
      "entityKey": "myRm5O5ZYOQvARW1kR/FsY1sVWvALsLSViv3lCEgcRg="
    },
    "headers": {
      "Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIwZDg0NjBmMy1mNmE0LTQwYjUtYjQ5ZS00YTFmMzdiNTdiZGYiLCJpYXQiOjE3MzE0MDc4MzYsImV4cCI6MTczMTQ1NDYzNn0.hw7iUG-wupQRQMy74h3GBQmTciQN7_cPRzB2BvkdU90"
    }
  }
}

2024-11-12 18:18 UTC, arnaudambro commented
en fait j'ai eu la même erreur une fois, mais là je ne l'ai plus, je n'arrive pas à reproduire...

2024-11-18 08:40 UTC, rap2hpoutre commented
Erreur en passant une action de "à faire" à "faite"

```
Error: Value is undefined, expected an Object
    at jsi_crypto_secretbox_easy (native)
    at crypto_secretbox_easy (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.sesan.mano&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:194727:46)
    at ?anon_0_ (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.sesan.mano&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:194291:97)
    at next (native)
    at asyncGeneratorStep (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.sesan.mano&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:24442:19)
    at _next (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.sesan.mano&modulesOnly=false&runModule=true&excludeSource=true&sourcePaths=url-server:24456:29)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)] {
  "extra": {
    "message": "error in updating action"
  }
}
```

2024-11-19 10:04 UTC, rap2hpoutre approved these changes

2024-11-19 13:01 UTC, merged